server:
  port: 8080

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5433/payments
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
